import 'package:flutter/material.dart';
import '../services/session.dart';

class ResumeScreen extends StatefulWidget {
  const ResumeScreen({super.key});

  @override
  State<ResumeScreen> createState() => _ResumeScreenState();
}

class _ResumeScreenState extends State<ResumeScreen> {
  final _skillsController = TextEditingController();
  final _projectsController = TextEditingController();
  final _targetRoleController = TextEditingController();
  String? _generatedResume;

  @override
  void dispose() {
    _skillsController.dispose();
    _projectsController.dispose();
    _targetRoleController.dispose();
    super.dispose();
  }

  void _generate() {
    final user = Session.currentUser!;
    final skills = _skillsController.text.trim().isEmpty ? 'Not specified' : _skillsController.text.trim();
    final projects = _projectsController.text.trim().isEmpty ? 'Not specified' : _projectsController.text.trim();
    final role = _targetRoleController.text.trim().isEmpty ? 'Internship / Entry-Level Role' : _targetRoleController.text.trim();

    setState(() {
      _generatedResume = '''
${user.name.toUpperCase()}
${user.email}
${user.college.isEmpty ? '' : user.college}${user.department.isEmpty ? '' : ' — ${user.department}'}${user.semester.isEmpty ? '' : ', Semester ${user.semester}'}

OBJECTIVE
Motivated ${user.department.isEmpty ? 'student' : user.department} student seeking a $role opportunity to apply
academic knowledge and hands-on project experience in a real-world setting.

EDUCATION
${user.college.isEmpty ? 'College name not provided' : user.college}
${user.department.isEmpty ? '' : '${user.department}, '}${user.semester.isEmpty ? '' : 'Semester ${user.semester}'}

SKILLS
$skills

PROJECTS
$projects

---
Generated by StudyMate AI Resume Builder (demo). Review and personalize before using.
''';
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('AI Resume Builder')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            TextField(
              controller: _targetRoleController,
              decoration: const InputDecoration(
                labelText: 'Target Role (e.g. Flutter Developer Intern)',
                border: OutlineInputBorder(),
              ),
            ),
            const SizedBox(height: 12),
            TextField(
              controller: _skillsController,
              decoration: const InputDecoration(
                labelText: 'Skills (comma separated)',
                border: OutlineInputBorder(),
              ),
              maxLines: 2,
            ),
            const SizedBox(height: 12),
            TextField(
              controller: _projectsController,
              decoration: const InputDecoration(
                labelText: 'Projects (brief description)',
                border: OutlineInputBorder(),
              ),
              maxLines: 3,
            ),
            const SizedBox(height: 16),
            FilledButton.icon(
              onPressed: _generate,
              icon: const Icon(Icons.auto_awesome),
              label: const Text('Generate Resume'),
            ),
            if (_generatedResume != null) ...[
              const SizedBox(height: 20),
              Card(
                child: Padding(
                  padding: const EdgeInsets.all(16),
                  child: SelectableText(_generatedResume!, style: const TextStyle(fontFamily: 'monospace', fontSize: 13)),
                ),
              ),
            ],
          ],
        ),
      ),
    );
  }
}
